# Copyright 2024 supercut-judge-cascade contributors
# SPDX-License-Identifier: MIT
"""Cosine-similarity identity filter for 1-vs-all face matching.

Legal notices
-------------
* Embeddings used by this module are typically generated by :mod:`arcface`,
  which relies on ``buffalo_l`` weights licensed for **NON-COMMERCIAL use
  only**.  See :mod:`supercut_cascade.arcface` for details.

* **GDPR Art. 9 / BIPA compliance**: Face embeddings are biometric data and
  may be subject to strict legal protections (EU GDPR Article 9, Illinois
  Biometric Information Privacy Act, and equivalent laws in other
  jurisdictions).  It is the **user's sole responsibility** to obtain all
  necessary consents and comply with applicable privacy law before
  building or querying an :class:`IdentityFilter`.

* Reference embeddings MUST NOT be committed to any repository or shared
  without the data-subject's explicit consent.  Store them exclusively in
  user-controlled, access-restricted directories.

Usage
-----
::

    from supercut_cascade.arcface import ArcFaceEmbedder
    from supercut_cascade.identity_filter import IdentityFilter, build_reference_embeddings

    embedder = ArcFaceEmbedder()

    # Build reference from a directory of face images
    ref_embs = build_reference_embeddings(
        image_paths=list(Path("reference/TARGET/").glob("*.jpg")),
        embedder=embedder,
        target_label="TARGET",
    )
    filt = IdentityFilter(reference_embeddings=ref_embs, threshold=0.40)

    is_match, sim = filt.is_target(query_embedding)
"""
from __future__ import annotations

import logging
from collections.abc import Sequence
from pathlib import Path

import numpy as np

from supercut_cascade.exceptions import IdentityFilterError

logger = logging.getLogger(__name__)


class IdentityFilter:
    """Cosine-similarity 1-vs-all identity filter.

    Compares a query embedding against the mean reference embedding computed
    from a set of known reference images.  Because all embeddings are
    L2-normalised, cosine similarity equals the dot product.

    Parameters
    ----------
    reference_embeddings : sequence of np.ndarray
        One or more 512-D L2-normalised embeddings representing the target
        identity.  Typically produced by :meth:`ArcFaceEmbedder.extract`.
    threshold : float
        Cosine-similarity threshold in [-1, 1].  Windows with similarity
        ``>= threshold`` are accepted as a match.  A value around ``0.40``
        works well for ArcFace ``buffalo_l`` embeddings.
    target_label : str
        Human-readable label used in log messages.  Defaults to ``"TARGET"``.
        **Do not embed personally identifiable names in production logs.**

    Raises
    ------
    IdentityFilterError
        If ``reference_embeddings`` is empty or all norms are zero.

    Notes
    -----
    * The mean reference vector is L2-renormalised after averaging so that
      the filter remains numerically stable even when reference embeddings
      are not perfectly equidistant.
    * **GDPR Art. 9 / BIPA**: Building this filter with real biometric data
      is the user's legal responsibility.  See module docstring.

    Examples
    --------
    >>> filt = IdentityFilter(reference_embeddings=[emb1, emb2], threshold=0.40)
    >>> is_match, sim = filt.is_target(query_emb)
    """

    def __init__(
        self,
        reference_embeddings: Sequence[np.ndarray],
        threshold: float = 0.40,
        target_label: str = "TARGET",
    ) -> None:
        if not reference_embeddings:
            raise IdentityFilterError(
                "reference_embeddings must contain at least one embedding."
            )

        ref_list = [np.asarray(e, dtype=np.float32) for e in reference_embeddings]
        for i, e in enumerate(ref_list):
            if e.shape != (512,):
                raise IdentityFilterError(
                    f"reference_embeddings[{i}] has shape {e.shape}; expected (512,)."
                )

        mean = np.mean(np.stack(ref_list, axis=0), axis=0)
        norm = float(np.linalg.norm(mean))
        if norm < 1e-6:
            raise IdentityFilterError(
                "Mean reference embedding has near-zero norm; cannot normalise."
            )

        self._ref: np.ndarray = (mean / norm).astype(np.float32)
        self.threshold = threshold
        self.target_label = target_label

        logger.info(
            "IdentityFilter ready (label=%r, n_refs=%d, threshold=%.3f, ref_norm=%.6f)",
            target_label,
            len(ref_list),
            threshold,
            float(np.linalg.norm(self._ref)),
        )

    @property
    def reference_embedding(self) -> np.ndarray:
        """L2-normalised mean reference embedding, shape ``(512,)``."""
        return self._ref

    def is_target(self, query_embedding: np.ndarray) -> tuple[bool, float]:
        """Test whether *query_embedding* matches the reference identity.

        Parameters
        ----------
        query_embedding : np.ndarray
            512-D L2-normalised ArcFace embedding to test.

        Returns
        -------
        is_match : bool
            ``True`` if cosine similarity is ``>= self.threshold``.
        similarity : float
            Cosine similarity in [-1, 1].

        Notes
        -----
        The query embedding is assumed to be L2-normalised (as produced by
        :meth:`ArcFaceEmbedder.extract`).  If your embedding source does not
        normalise, call ``emb / np.linalg.norm(emb)`` before passing.

        .. warning::
           Computing and persisting similarity scores for individuals may
           constitute biometric data processing under GDPR Art. 9 / BIPA.
        """
        q = np.asarray(query_embedding, dtype=np.float32)
        sim = float(np.dot(q, self._ref))
        return sim >= self.threshold, sim

    def score_batch(
        self, embeddings: np.ndarray, has_face: np.ndarray | None = None
    ) -> np.ndarray:
        """Compute cosine similarities for a batch of embeddings.

        Parameters
        ----------
        embeddings : np.ndarray
            Shape ``(N, 512)`` — rows are L2-normalised embeddings.
        has_face : np.ndarray or None
            Boolean mask of shape ``(N,)``.  Windows with ``has_face=False``
            receive similarity ``-1.0``.  If ``None``, all windows are scored.

        Returns
        -------
        np.ndarray
            Float32 array of shape ``(N,)`` with per-window similarity.
        """
        embs = np.asarray(embeddings, dtype=np.float32)
        sims: np.ndarray = embs @ self._ref
        if has_face is not None:
            sims = np.where(has_face, sims, np.float32(-1.0))
        return sims


def build_reference_embeddings(
    image_paths: Sequence[Path | str],
    embedder: object,
    target_label: str = "TARGET",
) -> list[np.ndarray]:
    """Embed reference face images and return per-image embeddings.

    Parameters
    ----------
    image_paths : sequence of Path or str
        Paths to face images (JPEG / PNG).  At least one image must yield a
        valid face detection.
    embedder : ArcFaceEmbedder
        An initialised :class:`~supercut_cascade.arcface.ArcFaceEmbedder`
        instance.  Accept any object with an ``extract(image)`` method to keep
        this function backend-agnostic.
    target_label : str
        Label used in log messages.  Defaults to ``"TARGET"``.

    Returns
    -------
    list of np.ndarray
        Successfully extracted 512-D embeddings.

    Raises
    ------
    IdentityFilterError
        If no valid face embedding could be obtained from any image.
    BackendUnavailableError
        Propagated from *embedder* if the backend is not installed.
    FileNotFoundError
        If *image_paths* is empty.

    Notes
    -----
    **GDPR Art. 9 / BIPA**: Processing reference face images constitutes
    biometric data processing.  Ensure you have a lawful basis before calling
    this function.

    Examples
    --------
    ::

        ref_embs = build_reference_embeddings(
            image_paths=sorted(Path("reference/TARGET/").glob("*.jpg")),
            embedder=ArcFaceEmbedder(),
            target_label="TARGET",
        )
        filt = IdentityFilter(reference_embeddings=ref_embs, threshold=0.40)
    """
    try:
        import cv2  # noqa: PLC0415
    except ImportError as exc:
        raise IdentityFilterError(
            "opencv-python is required: pip install opencv-python-headless"
        ) from exc

    paths = [Path(p) for p in image_paths]
    if not paths:
        raise FileNotFoundError("image_paths is empty; cannot build reference embedding.")

    embeddings: list[np.ndarray] = []
    for p in paths:
        img = cv2.imread(str(p))
        if img is None:
            logger.warning("Cannot read image: %s — skipping.", p)
            continue
        emb = embedder.extract(img)
        if emb is None:
            logger.warning("No face detected in %s — skipping.", p.name)
            continue
        logger.info("Reference image embedded OK: %s", p.name)
        embeddings.append(emb)

    if not embeddings:
        raise IdentityFilterError(
            f"No usable face embeddings obtained from {len(paths)} image(s) "
            f"(label={target_label!r}).  Check that the images contain a clear "
            "frontal face and that the ArcFace model is downloaded."
        )

    logger.info(
        "Built %d reference embedding(s) for label=%r.", len(embeddings), target_label
    )
    return embeddings
